version: "3.9"

services:
  web:
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules

  backend:
    build:
      context: BACKEND

    ports:
      - 3001:3001
    volumes:
      - ./BACKEND:/project
      - /BACKEND/node_modules
    environment:
      - NODE_ENV=development
